name: cuda-implementation build and test

on:
  push:
    branches:
      - 'main'
      - 'autotest'
  pull_request:
    branches:
      - 'main'
      - 'autotest'

jobs:
  build-cuda:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install NVIDIA CUDA Toolkit 11.7
        run: |
          # Add NVIDIA package repository
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
          sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
          wget https://developer.download.nvidia.com/compute/cuda/11.7.1/local_installers/cuda-repo-ubuntu2004-11-7-local_11.7.1-515.65.01-1_amd64.deb
          sudo dpkg -i cuda-repo-ubuntu2004-11-7-local_11.7.1-515.65.01-1_amd64.deb
          sudo cp /var/cuda-repo-ubuntu2004-11-7-local/cuda-*-keyring.gpg /usr/share/keyrings/
          sudo apt-get update
          sudo apt-get -y install cuda

          # Verify CUDA installation
          nvidia-smi
          nvcc --version

      - name: Install g++-11
        run: |
          sudo apt update
          sudo apt install -y g++-11
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
          g++ --version
          nvcc --version
          g++ --version

      - name: Build Project
        run: |
          cd ./cuda2-implementation
          make
          cd ..
      
      - name: Set up Python
        uses: actions/setup-python@v4  # Set up Python
        with:
          python-version: '3.9'  # Specify the Python version you need

      - name: Run Python Tests
        run: |
          cd ./testing
          python3 compare.py  ../cuda2-implementation 
          cd ..


